/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare class RawPocketOption {
  constructor(ssid: string)
  static newWithUrl(ssid: string, url: string): Promise<RawPocketOption>
  buy(asset: string, amount: number, time: number): Promise<Array<string>>
  sell(asset: string, amount: number, time: number): Promise<Array<string>>
  checkWin(tradeId: string): Promise<string>
  getDealEndTime(tradeId: string): Promise<number | null>
  getCandles(asset: string, period: number, offset: number): Promise<string>
  balance(): Promise<string>
  closedDeals(): Promise<string>
  clearClosedDeals(): Promise<void>
  openedDeals(): Promise<string>
  payout(): Promise<string>
  history(asset: string, period: number): Promise<string>
  subscribeSymbol(symbol: string): Promise<StreamIterator>
  subscribeSymbolChunked(symbol: string, chunkSize: number): Promise<StreamIterator>
  subscribeSymbolTimed(symbol: string, timeSeconds: number): Promise<StreamIterator>
}
export declare class StreamIterator {
  next(): Promise<string | null>
}
export declare class RawStreamIterator { }
