/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export type RawPocketOption = PocketOption
export declare class PocketOption { }
export declare class StreamIterator {
  next(): Promise<string | null>
}
export declare class RawStreamIterator { }
